source $VIMRUNTIME/vimrc_example.vim

au GUIEnter * simalt ~x


set gfn=Fixedsys:h17
set mouse=a
set number
set nobackup
set autochdir
set noundofile
set is
set cb=unnamed
set ts=4
set sw=4
set si


autocmd FileType python map <buffer> <M-1> :w<CR>:exec '!py' shellescape(@%, 1)<CR>
autocmd FileType python imap <buffer> <M-1> <esc>:w<CR>:exec '!py' shellescape(@%, 1)<CR>


cd C:\Users\mmvergara\Desktop\code\mmv-dsa\


if &diffopt !~# 'internal'
  set diffexpr=MyDiff()
endif
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg1 = substitute(arg1, '!', '\!', 'g')
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg2 = substitute(arg2, '!', '\!', 'g')
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let arg3 = substitute(arg3, '!', '\!', 'g')
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  let cmd = substitute(cmd, '!', '\!', 'g')
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction

command! -nargs=0 Run autocmd VimEnter * terminal python index.py



if has("gui_running")
  

  imap jj <Esc>
  imap JJ <Esc>
  imap <C-v> <C-r>+
  imap <C-z> <C-o>u
  nnoremap <C-Z> u
  vmap <C-z> u
  vmap <C-c> "+y<CR>
  vmap <C-v> "+p<CR>

  
  autocmd BufEnter * silent! lcd %:p:h

endif

